name: R-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

    - name: Install R package dependencies
      run: |
        Rscript -e 'install.packages(c("devtools", "testthat"), repos = "http://cran.rstudio.com")'
        Rscript -e 'devtools::install_deps(dependencies = TRUE)'

    - name: Run tests
      run: |
        Rscript -e 'devtools::test()'

    - name: Run checks
      run: |
        Rscript -e 'devtools::check()'
