name: R-testthat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        run: |
          if [ -f "install_dependencies.R" ]; then
            Rscript install_dependencies.R
          else
            echo "No install_dependencies.R found, skipping..."
          fi
          Rscript -e 'if (!requireNamespace("testthat", quietly = TRUE)) install.packages("testthat")'

      - name: Run tests with testthat
        run: |
          Rscript -e 'library(testthat); test_dir("tests/testthat", reporter = "summary")'
