name: R-testthat

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install additional dependencies
        run: |
          Rscript install_dependencies.R  # Custom script for any extra packages

      - name: Run tests with testthat
        run: |
          Rscript -e 'library(testthat); test_dir("tests/testthat")'
