name: R-testthat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        run: |
          # Install testthat and here packages if not already installed
          Rscript -e 'packages <- c("testthat", "here"); needed <- packages[!packages %in% installed.packages()]; if(length(needed)) install.packages(needed)'

      - name: Run tests with testthat
        run: |
          Rscript -e 'library(testthat); test_dir("tests/testthat", reporter = "summary")'
